modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="slave_mod"
version="0.1"
displayName="Slave Mod By Marias Productions XD"
credits="https://jirilabus.funsite.cz/"
displayURL="https://jirilabus.funsite.cz/"
logoFile="logo.png"
authors="Mar1as Productions"
description='''
Very cool mod everyone should try at least once in their lives
'''

[[dependencies.slave_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




