modLoader="javafml"
loaderVersion="[47,)"
license="Academic Free License v3.0"

[[mods]]
modId="slave_mod"
version="0.1"
displayName="Slave Mod By Marias Productions XD"
displayURL="https://jirilabus.funsite.cz/"
logoFile="logo.png"
credits="https://jirilabus.funsite.cz/"
authors="Mar1as Productions"
description="Very cool mod everyone should try at least once in their lives"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.slave_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



